### ISSUE TITLE
amigo - change the chat messages so that they have rounded edges

### ISSUE THREAD

**Issue by pureit-dev** [pureit-dev/chatapp#11]

**Comment by Amigo-The-Developer** [comment]
I've created a pull request addressing this issue
‎
amigo-change-the-chat-messages-so-that-they-have-rounded-edges-1721820511583
‎
I will update the chat message component to include rounded edges for the chat message bubbles.
‎
https://github.com/pureit-dev/chatapp/pull/12

**Comment by Amigo-The-Developer** [comment]
I've created a pull request addressing this issue
‎
amigo-change-the-chat-messages-so-that-they-have-rounded-edges-1721906999139
‎
This change involves updating the chat message component's styling to include rounded edges for a smoother, more visually appealing design. The modifications will be done in the chatMessage.tsx component by adding a class for rounded edges to the existing div element enclosing the chat messages.
‎
https://github.com/pureit-dev/chatapp/pull/13

**Comment by pureit-dev** [comment]
Before:
![image (1)](https://github.com/user-attachments/assets/9903bcc9-31e4-4484-8baf-43f1501576bb)

After:
![image (2)](https://github.com/user-attachments/assets/4d65b8cb-0fdd-4a75-8e01-e89e565f3407)

Merged and closing this issue
