### ISSUE TITLE
amigo - ChatBar component  does not extend to same width as ChatWindow

### ISSUE THREAD

**Issue by pureit-dev** [pureit-dev/chatapp#3]
The affected file is in src/components/sections/chatBar.tsx  It uses Tailwind inline styles rather then css files

**Comment by Amigo-The-Developer** [comment]
I've created a pull request addressing this issue
‎
amigo-chat-bar-component-does-not-extend-to-same-width-as-chat-window-1721632136674
‎
To ensure the ChatBar component extends to the same width as the ChatWindow component, the Tailwind CSS configuration will be adjusted to include custom styles that ensure consistency in width across these components.
‎
https://github.com/pureit-dev/chatapp/pull/4
